declare const version: any;
export { version };
export { debug } from './core/diag';
export { init } from './core/init';
export import core = require('./core');
export import model = require('./model');
export import query = require('./query');
export import security = require('./security');
export import web = require('./web');
export import connector = require('./connector');
export import livedata = require('./livedata');
